// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.1
// source: private.proto

package private

import (
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PlantsApiClient is the client API for PlantsApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PlantsApiClient interface {
}

type plantsApiClient struct {
	cc grpc.ClientConnInterface
}

func NewPlantsApiClient(cc grpc.ClientConnInterface) PlantsApiClient {
	return &plantsApiClient{cc}
}

// PlantsApiServer is the server API for PlantsApi service.
// All implementations must embed UnimplementedPlantsApiServer
// for forward compatibility
type PlantsApiServer interface {
	mustEmbedUnimplementedPlantsApiServer()
}

// UnimplementedPlantsApiServer must be embedded to have forward compatible implementations.
type UnimplementedPlantsApiServer struct {
}

func (UnimplementedPlantsApiServer) mustEmbedUnimplementedPlantsApiServer() {}

// UnsafePlantsApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PlantsApiServer will
// result in compilation errors.
type UnsafePlantsApiServer interface {
	mustEmbedUnimplementedPlantsApiServer()
}

func RegisterPlantsApiServer(s grpc.ServiceRegistrar, srv PlantsApiServer) {
	s.RegisterService(&PlantsApi_ServiceDesc, srv)
}

// PlantsApi_ServiceDesc is the grpc.ServiceDesc for PlantsApi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PlantsApi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "go.private.plants.PlantsApi",
	HandlerType: (*PlantsApiServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "private.proto",
}
